# Generated by Django 5.2.7 on 2025-11-14 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва секції')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('specialization', models.CharField(max_length=255, verbose_name='Спеціалізація')),
                ('price_per_session', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за заняття')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trainers/', verbose_name='Фото')),
                ('sections', models.ManyToManyField(to='api.section', verbose_name='Секції, які веде тренер')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В очікуванні'), ('confirmed', 'Підтверджено'), ('cancelled', 'Скасовано')], default='pending', max_length=10, verbose_name='Статус заявки')),
                ('booking_date', models.DateField(verbose_name='Дата заняття')),
                ('booking_time', models.TimeField(verbose_name='Час заняття')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trainer', verbose_name='Тренер')),
            ],
        ),
    ]
