# Generated by Django 5.2.7 on 2025-11-14 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='sections',
        ),
        migrations.AddField(
            model_name='trainer',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.section', verbose_name='Секція'),
        ),
    ]
