# Generated by Django 5.2.7 on 2025-12-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_section_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коментар клієнта'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='experience',
            field=models.PositiveIntegerField(default=1, help_text='Вкажіть кількість років досвіду', verbose_name='Стаж роботи (років)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category Name'),
        ),
    ]
